package com.msds.task.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.msds.task.entity.TimerTask;

public interface TimerTaskMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int countByExample(TimerTask example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int deleteByExample(TimerTask example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int insert(TimerTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int insertSelective(TimerTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	List<TimerTask> selectByExample(TimerTask example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	TimerTask selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int updateByExampleSelective(@Param("record") TimerTask record,
			@Param("example") TimerTask example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int updateByExample(@Param("record") TimerTask record,
			@Param("example") TimerTask example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int updateByPrimaryKeySelective(TimerTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int updateByPrimaryKey(TimerTask record);

	int updateByPrimaryTaskIdAndType(TimerTask timerTask);
}