package com.msds.task.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.msds.task.entity.TimerTaskLog;

public interface TimerTaskLogMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int countByExample(TimerTaskLog example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int deleteByExample(TimerTaskLog example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int insert(TimerTaskLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int insertSelective(TimerTaskLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	List<TimerTaskLog> selectByExample(TimerTaskLog example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	TimerTaskLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int updateByExampleSelective(@Param("record") TimerTaskLog record,
			@Param("example") TimerTaskLog example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int updateByExample(@Param("record") TimerTaskLog record,
			@Param("example") TimerTaskLog example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int updateByPrimaryKeySelective(TimerTaskLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table timer_task_log
	 * 
	 * @mbggenerated Fri May 09 20:02:25 CST 2014
	 */
	int updateByPrimaryKey(TimerTaskLog record);
}