package com.msds.task.entity;

import java.util.Date;

public class TimerTaskLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.id
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.task_id
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.task_name
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.type
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.task_type
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.task_class
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String taskClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.task_method
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String taskMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.run_time
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private Date runTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.real_run_time
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private Date realRunTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.complete_time
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private Date completeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.delay
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private Integer delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.intervers
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private Integer intervers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.status
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.task_content
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String taskContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.mobiles
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String mobiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.address
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer_task_log.subject
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    private String subject;

    private String orderByClause;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.id
     *
     * @return the value of timer_task_log.id
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.id
     *
     * @param id the value for timer_task_log.id
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.task_id
     *
     * @return the value of timer_task_log.task_id
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.task_id
     *
     * @param taskId the value for timer_task_log.task_id
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.task_name
     *
     * @return the value of timer_task_log.task_name
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.task_name
     *
     * @param taskName the value for timer_task_log.task_name
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.type
     *
     * @return the value of timer_task_log.type
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.type
     *
     * @param type the value for timer_task_log.type
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.task_type
     *
     * @return the value of timer_task_log.task_type
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.task_type
     *
     * @param taskType the value for timer_task_log.task_type
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.task_class
     *
     * @return the value of timer_task_log.task_class
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getTaskClass() {
        return taskClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.task_class
     *
     * @param taskClass the value for timer_task_log.task_class
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setTaskClass(String taskClass) {
        this.taskClass = taskClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.task_method
     *
     * @return the value of timer_task_log.task_method
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getTaskMethod() {
        return taskMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.task_method
     *
     * @param taskMethod the value for timer_task_log.task_method
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setTaskMethod(String taskMethod) {
        this.taskMethod = taskMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.run_time
     *
     * @return the value of timer_task_log.run_time
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public Date getRunTime() {
        return runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.run_time
     *
     * @param runTime the value for timer_task_log.run_time
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setRunTime(Date runTime) {
        this.runTime = runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.real_run_time
     *
     * @return the value of timer_task_log.real_run_time
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public Date getRealRunTime() {
        return realRunTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.real_run_time
     *
     * @param realRunTime the value for timer_task_log.real_run_time
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setRealRunTime(Date realRunTime) {
        this.realRunTime = realRunTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.complete_time
     *
     * @return the value of timer_task_log.complete_time
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.complete_time
     *
     * @param completeTime the value for timer_task_log.complete_time
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.delay
     *
     * @return the value of timer_task_log.delay
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public Integer getDelay() {
        return delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.delay
     *
     * @param delay the value for timer_task_log.delay
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setDelay(Integer delay) {
        this.delay = delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.intervers
     *
     * @return the value of timer_task_log.intervers
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public Integer getIntervers() {
        return intervers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.intervers
     *
     * @param intervers the value for timer_task_log.intervers
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setIntervers(Integer intervers) {
        this.intervers = intervers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.status
     *
     * @return the value of timer_task_log.status
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.status
     *
     * @param status the value for timer_task_log.status
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.task_content
     *
     * @return the value of timer_task_log.task_content
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getTaskContent() {
        return taskContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.task_content
     *
     * @param taskContent the value for timer_task_log.task_content
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setTaskContent(String taskContent) {
        this.taskContent = taskContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.mobiles
     *
     * @return the value of timer_task_log.mobiles
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getMobiles() {
        return mobiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.mobiles
     *
     * @param mobiles the value for timer_task_log.mobiles
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setMobiles(String mobiles) {
        this.mobiles = mobiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.address
     *
     * @return the value of timer_task_log.address
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.address
     *
     * @param address the value for timer_task_log.address
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timer_task_log.subject
     *
     * @return the value of timer_task_log.subject
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timer_task_log.subject
     *
     * @param subject the value for timer_task_log.subject
     *
     * @mbggenerated Fri May 09 20:02:25 CST 2014
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

	public String getOrderByClause() {
		return orderByClause;
	}

	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}
}